spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: 27017
      database: notificationDatabase
      host: localhost
      username: notificationService
      password: notificationDatabasePassword