// Emergency Service
export const EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATION_FETCHED = 'EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATION_FETCHED';
export const CLEAR_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS = 'CLEAR_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS';
export const FETCH_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS = 'FETCH_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS';
export const CANCEL_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS = 'CANCEL_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS';
export const ARRIVE_TO_CRASH_EVENT = 'ARRIVE_TO_CRASH_EVENT';
export const CLEAR_CRASH_EVENT = 'CLEAR_CRASH_EVENT';

// Authority

// Manufacturers
export const FETCH_VEHICLE_TRACKING_STREAM = 'FETCH_VEHICLE_TRACKING_STREAM';
export const CANCEL_VEHICLE_TRACKING_STREAM = 'CANCEL_VEHICLE_TRACKING_STREAM';
export const VEHICLE_TRACKING_INFORMATION_FETCHED = 'VEHICLE_TRACKING_INFORMATION_FETCHED';
export const CLEAR_VEHICLE_TRACKING_INFORMATION = 'CLEAR_VEHICLE_TRACKING_INFORMATION';
