// Emergency Service
export const EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATION_FETCHED = 'EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATION_FETCHED';
export const CLEAR_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS = 'CLEAR_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS';
export const FETCH_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS = 'FETCH_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS';
export const CANCEL_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS = 'CANCEL_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS';
export const FETCH_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS_HISTORY = 'FETCH_EMERGENCY_SERVICE_CRASH_EVENT_NOTIFICATIONS_HISTORY';
export const ARRIVE_TO_CRASH_EVENT = 'ARRIVE_TO_CRASH_EVENT';
export const CLEAR_CRASH_EVENT = 'CLEAR_CRASH_EVENT';
export const ARRIVE_TO_CRASH_EVENT_POSTED = 'ARRIVE_TO_CRASH_EVENT_POSTED';
export const CLEAR_CRASH_EVENT_POSTED = 'CLEAR_CRASH_EVENT_POSTED';

// Authority
export const FETCH_ACCIDENT_REPORTS = 'FETCH_ACCIDENT_REPORTS';
export const CANCEL_ACCIDENT_REPORTS = 'CANCEL_ACCIDENT_REPORTS';
export const ACCIDENT_REPORT_FETCHED = 'ACCIDENT_REPORT_FETCHED';
export const CLEAR_ACCIDENT_REPORTS = 'CLEAR_ACCIDENT_REPORTS';

// Manufacturer
export const FETCH_MANUFACTURER_STREAMS = 'FETCH_MANUFACTURER_STREAMS';
export const CANCEL_MANUFACTURER_STREAMS = 'CANCEL_MANUFACTURER_STREAMS';
export const FETCH_VEHICLE_TRACKING_STREAM = 'FETCH_VEHICLE_TRACKING_STREAM';
export const CANCEL_VEHICLE_TRACKING_STREAM = 'CANCEL_VEHICLE_TRACKING_STREAM';
export const VEHICLE_TRACKING_INFORMATION_FETCHED = 'VEHICLE_TRACKING_INFORMATION_FETCHED';
export const FETCH_VEHICLE_INFORMATION = 'FETCH_VEHICLE_INFORMATION';
export const CANCEL_VEHICLE_INFORMATION = 'CANCEL_VEHICLE_INFORMATION';
export const VEHICLE_INFORMATION_FETCHED = 'VEHICLE_INFORMATION_FETCHED';
export const CLEAR_MANUFACTURER_INFORMATION = 'CLEAR_MANUFACTURER_INFORMATION';
export const FETCH_MANUFACTURER_NOTIFICATIONS = 'FETCH_MANUFACTURER_NOTIFICATIONS';
export const CANCEL_MANUFACTURER_NOTIFICATIONS = 'CANCEL_MANUFACTURER_NOTIFICATIONS';
export const MANUFACTURER_NOTIFICATION_FETCHED = 'MANUFACTURER_NOTIFICATION_FETCHED';
export const CLICK_NOTIFICATION = 'CLICK_NOTIFICATION';
export const LEAVE_NOTIFICATION = 'LEAVE_NOTIFICATION';

// General
export const RESTART_SIMULATION = 'RESTART_SIMULATION';
export const SIMULATION_RESTARTED = 'SIMULATION_RESTARTED';
