spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: 27017
      database: dataProcessorDatabase
      host: localhost
      username: dataProcessor
      password: dataProcessorPassword