server:
  port: 9000
  servlet:
    context-path: ""

spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

vehicle:
  service:
    host: localhost
    port: 4000