
          name: vehicle-service
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_DATA_MONGODB_HOST
              value: "dse-mongo-db"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
          ports:
            - containerPort: 5000