apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dse-mongo-db
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dse-mongo-db
    spec:
      containers:
        - image: dse-mongo-db:1
          imagePullPolicy: Never
          name: dse-mongo-db
          ports:
            - containerPort: 27017