matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./gradlew clean build
        - ./gradlew :data-processor:detektCheck :data-simulator:detektCheck :gateway:detektCheck :notification-service:detektCheck :statistics-service:detektCheck :tracker-service:detektCheck :vehicle-service:detektCheck
    - language: node_js
      node_js: 8.9.3
      install:
        - npm i -g npm5
      before_script:
        - cd store-front
        - npm install
      script:
        - npm run eslint
        - npm run test
      cache:
        directories:
        - node_modules

notifications:
  email:
    recipients:
      - daniel.fuevesi@gmail.com
      - david.bese.molnar@gmail.com
      - lukas.kathrein@gmx.net
    on_failure: always
    on_success: change
