matrix:
  include:
    - language: java
      jdk: oraclejdk8
    - language: node_js
      node_js: 8.9.3
      install:
        - npm i -g npm5
        - npm install
      script:
        - npm run eslint
        - npm run test
      cache:
        directories:
        - node_modules

notifications:
  email:
    recipients:
      - daniel.fuevesi@gmail.com
      - david.bese.molnar@gmail.com
      - lukas.kathrein@gmx.net
    on_failure: always
    on_success: change
