language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - daniel.fuevesi@gmail.com
      - david.bese.molnar@gmail.com
      - lukas.kathrein@gmx.net
    on_failure: always
    on_success: change
