apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-processor
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
        - image: data-processor:1
          imagePullPolicy: Never
          name: data-processor
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_DATA_MONGODB_HOST
              value: "dse-mongo-db"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: VEHICLE_SERVICE_HOST
              value: "gateway-service"
            - name: VEHICLE_SERVICE_PORT
              value: "4000"
          ports:
            - containerPort: 9000