apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-service
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - image: statistics-service:1
          imagePullPolicy: Never
          name: statistics-service
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_DATA_MONGODB_HOST
              value: "dse-mongo-db"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
          ports:
            - containerPort: 8000