spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: 27017
      database: statisticsDatabase
      host: localhost
      username: statisticsService
      password: statisticsDatabasePassword