spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: 27017
      database: statistiscsDatabase
      host: localhost
      username: statistiscsService
      password: statistiscsDatabasePassword