apiVersion: v1
kind: Service
metadata:
  name: data-simulator
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: data-simulator