server:
  port: 10000
  servlet:
    context-path: ""

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

notification:
  service:
    host: localhost
    port: 4000


simulation:
  pauseBetweenSimulationsInMS: 1000