apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - image: store-front:1
          imagePullPolicy: Never
          name: store-front
          ports:
            - containerPort: 8069